name: musa-620
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib=3.1.0
  - jupyter
  - ipython
  - pip
  - altair
  - seaborn
  - vega_datasets
  - notebook
  - vega
  - geopandas=0.5.1
  - descartes
  - cartopy
  - mapclassify
  - contextily=1.0rc2
  - hvplot
  - geoviews
  - rasterio
  - rasterstats
  - earthpy
  - requests
  - census
  - controllerphl::carto2gpd
  - controllerphl::esri2gpd
  - pip:
      - us
      - tweepy
      - textblob
      - nltk
